create database CAPSTON_PROJECT;
select * from dbo.SALES;
ALTER TABLE dbo.SALES
ALTER COLUMN UnitPrice DECIMAL(10,2);

SELECT InvoiceDate
FROM dbo.SALES
WHERE TRY_CONVERT(DATETIME2, InvoiceDate, 101) IS NULL
  AND InvoiceDate IS NOT NULL;

BEGIN TRANSACTION;
ALTER TABLE dbo.SALES
ALTER COLUMN InvoiceDate DATETIME2;
COMMIT TRANSACTION;

---Task 1: Sales Performance Analysis

--total sales revenue generated for each month.
SELECT 
    FORMAT(InvoiceDate, 'yyyy-MM') AS SalesMonth,
   SUM(Quantity * UnitPrice) AS Revenue
FROM dbo.SALES
GROUP BY FORMAT(InvoiceDate, 'yyyy-MM')
ORDER BY SalesMonth;

-- month with the highest total revenue and the month with the lowest total revenue.

--Highest revenue month:
SELECT TOP 1
    YEAR(InvoiceDate) AS SalesYear,
    MONTH(InvoiceDate) AS SalesMonth,
    SUM(Quantity * UnitPrice) AS Revenue
FROM dbo.SALES
GROUP BY YEAR(InvoiceDate), MONTH(InvoiceDate)
ORDER BY Revenue DESC;
--Lowest revenue month:
SELECT TOP 1
    YEAR(InvoiceDate) AS SalesYear,
    MONTH(InvoiceDate) AS SalesMonth,
    SUM(Quantity * UnitPrice) AS Revenue
FROM dbo.SALES
GROUP BY YEAR(InvoiceDate), MONTH(InvoiceDate)
ORDER BY Revenue ASC;

--possible reasons why these months performed differently.
--1) Holiday shopping cycle: November's peak lines up with pre-Christmas wholesale restocking; retailers buy well ahead of the season to have stock ready.
--2) Partial months:December 2010 (data starts Dec 1) and December 2011 (data likely ends early-to-mid Dec) are incomplete calendar months, so their totals will look artificially low compared to full months.
--3) Wholesale buying behavior:Since many customers appear to be small resellers buying in bulk, order timing tends to cluster around a few big seasonal pushes rather than spreading evenly.  

---strategies the company could implement to improve sales during low-performing months.
--1) Off-season promotions and discounting
--2) Inventory and cash-flow planning, not just sales tactics
--3) Diversify seasonal product mix

---Task 2: Inventory Demand Analysis

--the five (5) products with the highest total quantity sold.
SELECT TOP 5
Description,
SUM(Quantity) as Highest_Total_Quantity
FROM dbo.SALES
GROUP BY Description
ORDER BY Highest_Total_Quantity DESC;

---Explain how this information can assist the inventory management team.
--1) Monthly revenue trends → demand forecasting
--2) Top 5 products by quantity sold → prioritized stock allocation
--3) Peak order hour (e.g., 10am–3pm UK time) → operational/fulfillment planning
--4) Low-performing months → avoiding overstock and dead capital

---Recommendation on how the company should adjust inventory levels based on your analysis.
--1) Clear seasonal stock aggressively post-peak
--2) Align regional stock with international demand patterns
--3) Use trading-day-normalized data, not raw monthly totals, for planning

---Task 3: Customer Ordering Behaviour
--Extract the hour from each order's purchase time.
SELECT 
    InvoiceDate,
    DATEPART(HOUR, InvoiceDate) AS OrderHour
FROM dbo.SALES;

--Determine which hour of the day records the highest number of customer orders.
SELECT TOP 1
    DATEPART(HOUR, InvoiceDate) AS OrderHour,
    COUNT(DISTINCT InvoiceNo) AS NumberOfOrders
FROM dbo.SALES
GROUP BY DATEPART(HOUR, InvoiceDate)
ORDER BY NumberOfOrders DESC;

SELECT 
    DATEPART(HOUR, InvoiceDate) AS OrderHour,
    COUNT(DISTINCT InvoiceNo) AS NumberOfOrders
FROM dbo.SALES
GROUP BY DATEPART(HOUR, InvoiceDate)
ORDER BY OrderHour;

---Recommend the best time for the company to send promotional emails, advertisements, or discount offers.
--1) Time of day: send during/just before the peak order window
--2) Day of week: worth checking, not yet analyzed
--3) Time of year: front-load campaigns ahead of known peak months

---Explain how this information could improve customer engagement and increase sales.
--1) Higher open and click-through rates
--2) Better conversion timing = shorter path from email to order
--3) Smoothing demand across the year

---Task 4: International Sales Analysis

--Exclude all sales made within the United Kingdom.
SELECT *
FROM dbo.SALES
WHERE Country <> 'United Kingdom';

--Calculate the total revenue generated by each remaining country.
SELECT 
    Country,
    SUM(Quantity * UnitPrice) AS Total_Revenue
FROM dbo.SALES
WHERE Quantity > 0 
    AND Country <> 'United Kingdom'
GROUP BY Country
ORDER BY Total_Revenue DESC;

--Identify the country with the highest international sales revenue.
SELECT TOP 1
    Country,
    SUM(Quantity * UnitPrice) AS Total_Revenue
FROM dbo.SALES
WHERE Quantity > 0 
    AND Country <> 'United Kingdom'
GROUP BY Country
ORDER BY Total_Revenue DESC;

---Discuss possible reasons why this country performs well.
--1) Geographic and logistical proximity: Countries close to the UK (Netherlands, Ireland, France, Germany) benefit from shorter shipping times and lower freight costs compared to more distant markets — making it easier and cheaper for wholesale buyers there to order regularly and in bulk.
--2) Established trading relationships / EU market access: At the time this dataset was recorded (2010–2011), the UK was still in the EU, meaning trade with other EU countries faced fewer customs/logistics barriers than non-EU markets. This likely made countries like Netherlands or Germany naturally easier and cheaper to sell into than, say, Australia or the US.
--3) Currency and pricing dynamics: Exchange rate conditions during 2010–2011 could have made UK goods relatively cheap for buyers in certain countries — a macro factor outside the company's direct control, but useful context.

---Recommend strategies for expanding sales in other international markets.
--1) Identify "lookalike" markets based on the top performer's traits
--2) Localized promotional timing
--3) Test smaller markets with low-cost pilot campaigns
--4) Address logistics friction directly